### ISSUE TITLE
Please add checksums for ZIPs and executables

### ISSUE THREAD

**Issue by swamp-agr** [aya-prover/aya-prover-docs#13]
On the installation page I see direct links to ZIP archives and executables. What I am missing is checksums for the files. So I am not quite sure what I am about to download.

Could you please add them?

**Comment by ice1000** [comment]
Good idea💡! /cc @imkiva

**Comment by ice1000** [comment]
Hi, I am unfamiliar with file checksums. Could you please tell me how to generate file checksums on Ubuntu/macOS/Windows? A link to some referential materials should be fine. I googled and there seem to be several ways, and I don't think I can figure out a standard approach.

**Comment by swamp-agr** [comment]
Ubuntu/MacOS: ` sha256sum <filename>`.

**Comment by ice1000** [comment]
@swamp-agr Hi, it should be fixed in latest push to the main branch. Lmk if you find the file formats problematic.
